add_newline = false

[line_break]
disabled = true

[character]                            
success_symbol = "[λ](bold green)"     
error_symbol = "[λ](bold red)"     
vicmd_symbol= "[λ](bold blue)"

[hostname]
ssh_only = true
format = "[$hostname]($style) "
trim_at = "-"
style = "bold yellow"
disabled = false

[username]
style_user = "bold blue"
show_always = true

[nodejs]
style = "bold yellow"
